name = "taboo-chat"
account_id = "1a4c79c0c70ad1ed652598139ba058e2"

type = "webpack"
workers_dev = true

# route = ""
# zone_id = ""
compatibility_date = "2021-10-20"

[site]
bucket = "./build"
include = ["*"]

[env.dev]
zone_id = "614fdc6827bbdbc617a016531e1a3c83"

# The route pattern your Workers application will be served at
route = "taboo-dev.e-ardi.online/*"

[env.staging]
zone_id = "614fdc6827bbdbc617a016531e1a3c83"

# The route pattern your Workers application will be served at
route = "taboo-staging.e-ardi.online/*"

[env.production]
# The ID of the domain to deploying to
zone_id = "614fdc6827bbdbc617a016531e1a3c83"

# The route pattern your Workers application will be served at
route = "taboo.e-ardi.online/*"
