version: '3'
services:
  taboo-api:
    build: .
    depends_on:
      - redis
    ports:
      - '8001:8080'
    environment:
      - REDIS_HOST=redis
      - SERVICE_PORT=8080
    env_file:
      - .env
  redis:
    image: 'redis'
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    restart: always
