# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Taboo UI to dev environment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: cp .env{.example,}
      - run: sed -i ''  's#{{apiBaseUrl}}#https://taboo-api-dev.uksouth.cloudapp.azure.com#g' .env
      - run: yarn build
        env:
          REACT_APP_API_URL: https://taboo-api-dev.uksouth.cloudapp.azure.com

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn deploy dev
        env:
          CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
